services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_mini_14
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ..:/app
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: ledger-db
    environment:
      - POSTGRES_USER=ledger-user
      - POSTGRES_PASSWORD=ledger-password
      - POSTGRES_DB=ledger
    volumes:
      - db-data:/var/lib/postgresql/data  
    ports:
      - "5500:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger-user -d ledger"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: